# Operating Systems Assignment 2 part 1 makefile
# Blessed Chitamba
# April 2019

JAVAC=javac
.SUFFIXES: .java .class

# SRCDIR=src
# BINDIR=bin

%.class:%.java
	$(JAVAC) -d -cp $*.java

CLASSES=BThread.class Barrier.class BarrierTest.class
CLASS_FILES=$(CLASSES:%.class=%.class)

default: $(CLASS_FILES)

clean:
	rm *.class
